org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.248
loader_version_range=[4,)
jei_version=19.44.0.403

mod_id=bioforge
mod_name=BioForge
mod_license=All Rights Reserved
mod_version=2.1
mod_group_id=net.jenkimods.bioforge
mod_authors=JenkiMods(Coder), Soravis(Main Tester), Test6192(Tester), MrDuckly69(Tester), Alterverses(Tester), CaptainB(Tester), luke_is_pickles(Tester)
mod_description=Dive into a world of evolving danger with BioForge, where infections are alive, adaptive, and deadly. Create, study, and combat unique pathogens using the Microscope, Vaccine Maker, Chemical Synthesizer, and other laboratory equipment. Manipulate viral traits, craft life-saving treatments, or unleash chaos.
